name: Deploy documentation to Pages

on: [push, pull_request, workflow_dispatch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install pdoc
        run: |
          pip install pdoc
      - name: pdoc build
        run: |
          pdoc --docformat "google" mattenklopper -o ./docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload docs
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
